"""Decision-path microbenchmark. `make bench` / `python tools/bench.py`.

Measures parse + resolve + decide + rewrite over a corpus and enforces the budget from README
(p95 < 10 ms) using a snapshot compiled from live DataHub - the same graph production decides
against. Exits non-zero on a regression so CI fails the build. Writes docs/benchmarks.md. Needs
`demo/up.py`.
"""

from __future__ import annotations

import statistics
import sys
import time

from _common import ROOT, live_snapshot, load_demo_config
from airlock.analyzer.resolve import resolve
from airlock.analyzer.rewrite import rewrite
from airlock.engine.decide import decide

BUDGET_MS = 10.0
CACHE_BUDGET_MS = 1.0  # a repeat query must skip parse/resolve/decide/rewrite entirely
CORPUS = [
    "SELECT name, email, ssn FROM dim_users",
    "SELECT u.name, u.email, o.total FROM users_raw u JOIN orders o ON o.user_id = u.id LIMIT 50",
    "WITH t AS (SELECT email, id FROM dim_users) SELECT email FROM t",
    "SELECT status, COUNT(*) FROM orders GROUP BY status",
    "SELECT * FROM dim_users ORDER BY id",
    "SELECT COUNT(DISTINCT email) FROM dim_users",
]


def main() -> int:
    cfg = load_demo_config()
    graph = live_snapshot(cfg)  # real snapshot from live DataHub
    principal = graph.principal("growth-agent")

    for sql in CORPUS:  # warm caches / import paths
        r = resolve(sql, dialect="duckdb", graph=graph, enforcement=graph.enforcement)
        decide(r, principal, graph)

    samples: list[float] = []
    for _ in range(2000):
        sql = CORPUS[len(samples) % len(CORPUS)]
        start = time.perf_counter()
        r = resolve(sql, dialect="duckdb", graph=graph, enforcement=graph.enforcement)
        decide(r, principal, graph)
        rewrite(r, principal, graph)
        samples.append((time.perf_counter() - start) * 1000)

    samples.sort()
    p50 = samples[len(samples) // 2]
    p95 = samples[int(len(samples) * 0.95)]
    p99 = samples[int(len(samples) * 0.99)]
    mean = statistics.mean(samples)
    print(
        f"decision p50={p50:.3f}ms p95={p95:.3f}ms p99={p99:.3f}ms mean={mean:.3f}ms (n={len(samples)})"
    )

    cached_p95 = _bench_cache_hit(cfg, graph)
    _write_doc(p50, p95, p99, mean, cached_p95)
    if p95 > BUDGET_MS:
        print(f"REGRESSION: p95 {p95:.3f}ms exceeds budget {BUDGET_MS}ms", file=sys.stderr)
        return 1
    if cached_p95 > CACHE_BUDGET_MS:
        print(
            f"REGRESSION: cache-hit p95 {cached_p95:.3f}ms exceeds {CACHE_BUDGET_MS}ms",
            file=sys.stderr,
        )
        return 1
    print(f"within budget (p95 < {BUDGET_MS}ms, cache hit < {CACHE_BUDGET_MS}ms)")
    return 0


def _bench_cache_hit(cfg: object, graph: object) -> float:
    """Repeat-query latency: the decision cache's whole reason to exist.

    Measures the gateway's plan path rather than the analyzer directly, because the cache lives in
    the gateway and keys on `(sql, principal, snapshot_hash)`. The first call populates it; every
    later call for the same key must skip parse, resolve, decide, and rewrite entirely.
    """
    import tempfile

    from airlock.exec.duckdb_adapter import DuckdbAdapter
    from airlock.gateway import Gateway
    from airlock.policy.store import SnapshotStore

    store = SnapshotStore(str(ROOT / ".airlock" / "bench.sqlite"))
    store.install(graph)  # type: ignore[arg-type]
    gateway = Gateway(cfg, store, DuckdbAdapter(tempfile.mktemp(suffix=".duckdb")), [])  # type: ignore[arg-type]
    sql = CORPUS[0]
    gateway.dry_run(sql, "growth-agent")  # populate

    samples: list[float] = []
    for _ in range(2000):
        start = time.perf_counter()
        gateway.dry_run(sql, "growth-agent")
        samples.append((time.perf_counter() - start) * 1000)
    samples.sort()
    p95 = samples[int(len(samples) * 0.95)]
    print(f"cache hit  p50={samples[len(samples) // 2]:.3f}ms p95={p95:.3f}ms (n={len(samples)})")
    return p95


def _write_doc(p50: float, p95: float, p99: float, mean: float, cached_p95: float) -> None:
    doc = ROOT / "docs" / "benchmarks.md"
    doc.parent.mkdir(exist_ok=True)
    doc.write_text(
        "# Benchmarks\n\n"
        "Decision overhead (parse + resolve + decide + rewrite) on the benchmark corpus, "
        "regenerated by `make bench`.\n\n"
        "| metric | value |\n|---|---|\n"
        f"| p50 | {p50:.3f} ms |\n| p95 | {p95:.3f} ms |\n| p99 | {p99:.3f} ms |\n"
        f"| mean | {mean:.3f} ms |\n| budget (p95) | {BUDGET_MS:.1f} ms |\n\n"
        "Repeat query served from the decision cache, keyed on "
        "`(sql, principal, snapshot_hash)`. A policy change moves the hash, so a stale entry is "
        "unreachable rather than merely expired.\n\n"
        "| metric | value |\n|---|---|\n"
        f"| cache hit p95 | {cached_p95:.3f} ms |\n"
        f"| budget (p95) | {CACHE_BUDGET_MS:.1f} ms |\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    from _common import run

    run(main)
