"""Decision-path microbenchmark. `make bench` / `python tools/bench.py`.

Measures parse + resolve + decide + rewrite over a corpus and enforces the budget from README
(p95 < 10 ms) using a snapshot compiled from live DataHub - the same graph production decides
against. Exits non-zero on a regression so CI fails the build. Writes docs/benchmarks.md. Needs
`demo/up.py`.
"""

from __future__ import annotations

import statistics
import sys
import time

from _common import ROOT, live_snapshot, load_demo_config
from airlock.analyzer.resolve import resolve
from airlock.analyzer.rewrite import rewrite
from airlock.engine.decide import decide

BUDGET_MS = 10.0
CORPUS = [
    "SELECT name, email, ssn FROM dim_users",
    "SELECT u.name, u.email, o.total FROM users_raw u JOIN orders o ON o.user_id = u.id LIMIT 50",
    "WITH t AS (SELECT email, id FROM dim_users) SELECT email FROM t",
    "SELECT status, COUNT(*) FROM orders GROUP BY status",
    "SELECT * FROM dim_users ORDER BY id",
    "SELECT COUNT(DISTINCT email) FROM dim_users",
]


def main() -> int:
    cfg = load_demo_config()
    graph = live_snapshot(cfg)  # real snapshot from live DataHub
    principal = graph.principal("growth-agent")

    for sql in CORPUS:  # warm caches / import paths
        r = resolve(sql, dialect="duckdb", graph=graph, enforcement=graph.enforcement)
        decide(r, principal, graph)

    samples: list[float] = []
    for _ in range(2000):
        sql = CORPUS[len(samples) % len(CORPUS)]
        start = time.perf_counter()
        r = resolve(sql, dialect="duckdb", graph=graph, enforcement=graph.enforcement)
        decide(r, principal, graph)
        rewrite(r, principal, graph)
        samples.append((time.perf_counter() - start) * 1000)

    samples.sort()
    p50 = samples[len(samples) // 2]
    p95 = samples[int(len(samples) * 0.95)]
    p99 = samples[int(len(samples) * 0.99)]
    mean = statistics.mean(samples)
    print(
        f"decision p50={p50:.3f}ms p95={p95:.3f}ms p99={p99:.3f}ms mean={mean:.3f}ms (n={len(samples)})"
    )

    _write_doc(p50, p95, p99, mean)
    if p95 > BUDGET_MS:
        print(f"REGRESSION: p95 {p95:.3f}ms exceeds budget {BUDGET_MS}ms", file=sys.stderr)
        return 1
    print(f"within budget (p95 < {BUDGET_MS}ms)")
    return 0


def _write_doc(p50: float, p95: float, p99: float, mean: float) -> None:
    doc = ROOT / "docs" / "benchmarks.md"
    doc.parent.mkdir(exist_ok=True)
    doc.write_text(
        "# Benchmarks\n\n"
        "Decision overhead (parse + resolve + decide + rewrite) on the benchmark corpus, "
        "regenerated by `make bench`.\n\n"
        "| metric | value |\n|---|---|\n"
        f"| p50 | {p50:.3f} ms |\n| p95 | {p95:.3f} ms |\n| p99 | {p99:.3f} ms |\n"
        f"| mean | {mean:.3f} ms |\n| budget (p95) | {BUDGET_MS:.1f} ms |\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    from _common import run

    run(main)
