"""Regenerate examples/ - captured envelopes and before/after SQL from the live demo stack.

Run: `python tools/gen_examples.py` (or `make examples`) with the demo stack up (`python demo/up.py`).
Never hand-edit examples/; this is the source of truth so the folder can't go stale (CLAUDE.md §2).
Every envelope here is produced by the real gateway over a snapshot compiled from live DataHub and a
real DuckDB warehouse - the exact path the demo runs - so these are captures, not fabrications.
"""

from __future__ import annotations

import json

from _common import ROOT, live_snapshot, load_demo_config, seed_warehouse
from airlock.audit.record import AuditRecord
from airlock.engine.verdicts import Envelope
from airlock.exec.duckdb_adapter import DuckdbAdapter
from airlock.gateway import Gateway
from airlock.policy.store import SnapshotStore

EXAMPLES = ROOT / "examples"

CASES = [
    (
        "01_clean_aggregate",
        "growth-agent",
        "SELECT status, COUNT(*) AS n, ROUND(SUM(total), 2) AS revenue "
        "FROM orders GROUP BY status ORDER BY revenue DESC",
    ),
    ("02_pii_masked", "growth-agent", "SELECT name, email, phone FROM dim_users LIMIT 5"),
    (
        "03_deprecated_substituted",
        "growth-agent",
        "SELECT u.name, u.email, u.ssn, o.total FROM users_raw u "
        "JOIN orders o ON o.user_id = u.id ORDER BY o.total DESC LIMIT 10",
    ),
    (
        "04_predicate_denied",
        "growth-agent",
        "SELECT name FROM dim_users WHERE email = 'ada@corp.com'",
    ),
    ("05_cross_domain_denied", "growth-agent", "SELECT name, salary FROM payroll"),
    ("06_natural_language_rejected", "growth-agent", "show me the biggest spenders this quarter"),
    (
        "07_complex_cte_window",
        "growth-agent",
        "WITH ranked AS (SELECT name, email, ROW_NUMBER() OVER (ORDER BY signup_date DESC) AS rn "
        "FROM dim_users) SELECT name, email FROM ranked WHERE rn <= 3",
    ),
]


async def main() -> None:
    EXAMPLES.mkdir(exist_ok=True)
    cfg = load_demo_config()
    warehouse = seed_warehouse(cfg)
    graph = live_snapshot(cfg)  # compiled from live DataHub - fails loudly if the stack is down

    store = SnapshotStore(str(ROOT / ".airlock" / "examples.sqlite"))
    store.install(graph)
    gateway = Gateway(cfg, store, DuckdbAdapter(warehouse), [])

    try:
        before_after: list[str] = []
        audit_lines: list[str] = []
        for i, (name, principal, sql) in enumerate(CASES, 1):
            env = await gateway.run_query(sql, principal)
            # Stable request id so `make examples` is a no-op unless behavior actually changed.
            env = env.model_copy(update={"request_id": f"req_example_{i:02d}"})
            payload = json.loads(env.model_dump_json())
            (EXAMPLES / f"{name}.json").write_text(
                json.dumps(payload, indent=2) + "\n", encoding="utf-8"
            )
            before_after.append(_before_after(name, env.original_sql, env.executed_sql))
            audit_lines.append(_audit_line(env))
            print(f"wrote examples/{name}.json  [{env.status}]")

        (EXAMPLES / "before_after.sql").write_text("\n".join(before_after), encoding="utf-8")
        (EXAMPLES / "audit.jsonl").write_text("\n".join(audit_lines) + "\n", encoding="utf-8")
        (EXAMPLES / "README.md").write_text(_readme(), encoding="utf-8")
    finally:
        await gateway.aclose()


def _audit_line(env: Envelope) -> str:
    """One deterministic audit record per example (fixed ts/latency so the file is reproducible)."""
    record = AuditRecord.from_envelope(env, latency_ms=0.0, warehouse="duckdb")
    record = record.model_copy(update={"ts": "2026-07-21T00:00:00+00:00"})
    return record.model_dump_json()


def _before_after(name: str, before: str, after: str | None) -> str:
    lines = [f"-- {name}", "-- before:", f"{before};", "-- after:"]
    lines.append(f"{after};" if after else "-- <denied - not executed>")
    return "\n".join(lines) + "\n"


def _readme() -> str:
    rows = "\n".join(f"- `{name}.json` - {sql}" for name, _, sql in CASES)
    return (
        "# examples\n\n"
        "Captured request/response envelopes and before/after SQL, regenerated by "
        "`python tools/gen_examples.py` (`make examples`) against the live demo stack. Each envelope "
        "comes from the real gateway over a policy snapshot compiled from a live DataHub and a real "
        "DuckDB warehouse - the same path the demo runs. Do not hand-edit.\n\n"
        f"{rows}\n\n"
        "`before_after.sql` pairs each original query with the SQL Airlock actually executed. "
        "`audit.jsonl` is the decision log from this run.\n"
    )


if __name__ == "__main__":
    from _common import run

    run(main)
